name = "rusoblanco"
license = "MIT"
licenselink = "https://github.com/nilp0inter/rusoblanco-hugo-theme/blob/main/LICENSE"
description = "rusoblanco personal theme - A customized version of the classic NanoBlogger theme"
homepage = "https://github.com/nilp0inter/rusoblanco-hugo-theme"
tags = ["blog", "minimal", "clean", "simple", "sidebar", "classic", "nanoblogger", "rusoblanco", "personal"]
features = ["blog", "calendar", "archives", "categories", "rss", "code-highlighting", "math"]
min_version = "0.112.0"

[author]
  name = "nilp0inter"
  homepage = "https://github.com/nilp0inter"

[original]
  name = "www.rusoblanco.com"
  author = "nilp0inter"
  homepage = "https://www.rusoblanco.com"
  description = "Original www.rusoblanco.com blog from the 2000s"

[basedOn]
  name = "NanoBlogger"
  author = "n1xt3r"
  homepage = "https://nanoblogger.sourceforge.net/"
  license = "GPL"
  description = "Original NanoBlogger static site generator that inspired this theme"
